# Generated by Django 5.2.3 on 2025-06-17 07:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Student Full Name')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='Student Email')),
                ('semester', models.CharField(choices=[('SEM_ONE', 'Semester One'), ('SEM_TWO', 'Semester Two'), ('SEM_THREE', 'Semester Three'), ('SEM_FOUR', 'Semester Four'), ('SEM_FIVE', 'Semester Five'), ('SEM_SIX', 'Semester Six'), ('SEM_SEVEN', 'Semester Seven'), ('SEM_EIGHT', 'Semester Eight')], default='N/A', max_length=20, null=True)),
                ('phone_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['-full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Teacher Full Name')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='Teacher Email')),
                ('department', models.CharField(choices=[('BCA', 'Bachelor of Computer Application'), ('BCT', 'Bachelor of Computer Engineering'), ('BEI', 'Bachelor of Electronics and Information'), ('BCE', 'Bachelor of Civil Engineering')], default='N/A', max_length=20, null=True)),
                ('phone_no', models.IntegerField()),
                ('join_date', models.DateField(default='Join Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['-full_name'],
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Chapter Full Name')),
                ('Materials', models.CharField(blank=True, choices=[('SLIDES', 'Chapter Slides'), ('TEXT_BOOK', 'Text Book'), ('REFERENCE_BOOK', 'Word files'), ('OLD_QUESTIONS', 'Question Collections'), ('AUDIO_BOOK', 'An Audio Book')], default='N/A', max_length=50, null=True, verbose_name='Materials')),
                ('descriptions', models.CharField(default='N/A', max_length=255, verbose_name='Description ')),
                ('subject', models.CharField(choices=[('BCT001', 'Software engineering'), ('BCT002', 'System Analysis and Design'), ('BCT003', 'Operating Systems'), ('BCT004', 'Object Oriented Programming'), ('BCT005', 'Electronics and Instrumentation')], default='N/A', max_length=20, verbose_name='Subject')),
                ('material_file', models.FileField(default='N/A', upload_to='material/', verbose_name='Select File')),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2025, 6, 17, 13, 30, 32, 643560), verbose_name='Upload Time')),
                ('teacher', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('start_date', models.DateField(default='Start Date', verbose_name='Start Date')),
                ('end_date', models.DateField(default='End Date', verbose_name='End Date')),
                ('question_file', models.FileField(null=True, upload_to='assignment/questions/', verbose_name='Select Assignment File')),
                ('question', models.FileField(blank=True, null=True, upload_to='', verbose_name='Assignment Question')),
                ('remark', models.CharField(max_length=100, verbose_name='Assignment Details')),
                ('full_marks', models.FloatField()),
                ('subject', models.CharField(choices=[('BCT001', 'Software engineering'), ('BCT002', 'System Analysis and Design'), ('BCT003', 'Operating Systems'), ('BCT004', 'Object Oriented Programming'), ('BCT005', 'Electronics and Instrumentation')], default='N/A', max_length=20, verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['-title'],
            },
        ),
    ]
